// <auto-generated />
using System;
using AIPBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIPBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120153000_UpdateDailyOccurrenceBookSchema")]
    partial class UpdateDailyOccurrenceBookSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Use reflection to call the protected BuildModel method from the snapshot
            var snapshot = new ApplicationDbContextModelSnapshot();
            var buildModelMethod = typeof(ApplicationDbContextModelSnapshot).GetMethod("BuildModel", 
                System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            buildModelMethod?.Invoke(snapshot, new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}

