using AIPBackend.Models;
using AIPBackend.Models.DTOs;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations;

namespace AIPBackend.Services
{
    public class HolidayService : IHolidayService
    {
        private readonly ILogger<HolidayService> _logger;
        private readonly IHolidayEmailService _holidayEmailService;
        private readonly UserManager<ApplicationUser> _userManager;

        public HolidayService(
            ILogger<HolidayService> logger,
            IHolidayEmailService holidayEmailService,
            UserManager<ApplicationUser> userManager)
        {
            _logger = logger;
            _holidayEmailService = holidayEmailService;
            _userManager = userManager;
        }

        public async Task<HolidayRequestResponseDto> SubmitHolidayRequestAsync(HolidayRequestSubmissionDto request, int employeeId, string currentUserId)
        {
            try
            {
                _logger.LogInformation("Submitting holiday request for employee {EmployeeId}", employeeId);

                // Validate request
                var validationErrors = ValidateHolidayRequest(request);
                if (validationErrors.Any())
                {
                    throw new ValidationException($"Holiday request validation failed: {string.Join(", ", validationErrors)}");
                }

                // Check for conflicts
                var conflicts = await CheckHolidayConflictsAsync(request.StartDate, request.EndDate, employeeId);
                if (conflicts.Any())
                {
                    _logger.LogWarning("Holiday request conflicts detected for employee {EmployeeId}", employeeId);
                }

                // Create holiday request (placeholder - implement with your repository)
                var holidayRequest = new HolidayRequestResponseDto
                {
                    Id = 1, // This would be generated by your repository
                    EmployeeId = employeeId,
                    EmployeeName = "User", // This would come from user service
                    EmployeeEmail = "user@company.com", // This would come from user service
                    StartDate = request.StartDate,
                    EndDate = request.EndDate,
                    NumberOfDays = request.NumberOfDays,
                    HolidayType = request.HolidayType,
                    Reason = request.Reason,
                    Comments = request.Comments,
                    Status = "Pending",
                    CreatedAt = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow,
                    IsHalfDay = request.IsHalfDay,
                    HalfDayType = request.HalfDayType
                };

                // Get user details for email notification (using EmployeeId field as legacy mapping)
                var allUsers = _userManager.Users.ToList();
                var user = allUsers.FirstOrDefault(u => u.EmployeeId == employeeId);
                if (user != null && !string.IsNullOrWhiteSpace(user.Email))
                {
                    // Send notification to manager
                    try
                    {
                        var managerEmail = "manager@company.com"; // This would come from your user/manager relationship
                        await _holidayEmailService.SendHolidayRequestSubmittedNotificationAsync(holidayRequest, user, managerEmail);
                        _logger.LogInformation("Holiday request submitted notification sent to manager");
                    }
                    catch (Exception emailEx)
                    {
                        _logger.LogWarning(emailEx, "Failed to send holiday request submitted notification");
                    }

                    // Send conflict notification if conflicts exist
                    if (conflicts.Any())
                    {
                        try
                        {
                            await _holidayEmailService.SendHolidayRequestConflictNotificationAsync(holidayRequest, user, conflicts.ToList());
                            _logger.LogInformation("Holiday request conflict notification sent to user");
                        }
                        catch (Exception emailEx)
                        {
                            _logger.LogWarning(emailEx, "Failed to send holiday request conflict notification");
                        }
                    }
                }

                _logger.LogInformation("Holiday request submitted successfully for employee {EmployeeId}", employeeId);
                return holidayRequest;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error submitting holiday request for employee {EmployeeId}", employeeId);
                throw;
            }
        }

        public async Task<bool> ApproveHolidayRequestAsync(int requestId, string approvedBy, string? comments = null)
        {
            try
            {
                _logger.LogInformation("Approving holiday request {RequestId} by {ApprovedBy}", requestId, approvedBy);

                // Get holiday request (placeholder - implement with your repository)
                var holidayRequest = new HolidayRequestResponseDto
                {
                    Id = requestId,
                    EmployeeId = 1,
                    EmployeeName = "User",
                    EmployeeEmail = "user@company.com",
                    Status = "Approved",
                    ApprovedBy = approvedBy,
                    ApprovedDate = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow
                };

                // Get user details for email notification (using EmployeeId field as legacy mapping)
                var allUsers = _userManager.Users.ToList();
                var user = allUsers.FirstOrDefault(u => u.EmployeeId == holidayRequest.EmployeeId);
                if (user != null && !string.IsNullOrWhiteSpace(user.Email))
                {
                    try
                    {
                        await _holidayEmailService.SendHolidayRequestApprovedNotificationAsync(holidayRequest, user, approvedBy);
                        _logger.LogInformation("Holiday request approved notification sent to user");
                    }
                    catch (Exception emailEx)
                    {
                        _logger.LogWarning(emailEx, "Failed to send holiday request approved notification");
                    }
                }

                _logger.LogInformation("Holiday request {RequestId} approved successfully", requestId);
                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error approving holiday request {RequestId}", requestId);
                throw;
            }
        }

        public async Task<bool> RejectHolidayRequestAsync(int requestId, string rejectedBy, string rejectionReason)
        {
            try
            {
                _logger.LogInformation("Rejecting holiday request {RequestId} by {RejectedBy}", requestId, rejectedBy);

                // Get holiday request (placeholder - implement with your repository)
                var holidayRequest = new HolidayRequestResponseDto
                {
                    Id = requestId,
                    EmployeeId = 1,
                    EmployeeName = "User",
                    EmployeeEmail = "user@company.com",
                    Status = "Rejected",
                    RejectedBy = rejectedBy,
                    RejectionReason = rejectionReason,
                    RejectedDate = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow
                };

                // Get user details for email notification (using EmployeeId field as legacy mapping)
                var allUsers = _userManager.Users.ToList();
                var user = allUsers.FirstOrDefault(u => u.EmployeeId == holidayRequest.EmployeeId);
                if (user != null && !string.IsNullOrWhiteSpace(user.Email))
                {
                    try
                    {
                        await _holidayEmailService.SendHolidayRequestRejectedNotificationAsync(holidayRequest, user, rejectedBy, rejectionReason);
                        _logger.LogInformation("Holiday request rejected notification sent to user");
                    }
                    catch (Exception emailEx)
                    {
                        _logger.LogWarning(emailEx, "Failed to send holiday request rejected notification");
                    }
                }

                _logger.LogInformation("Holiday request {RequestId} rejected successfully", requestId);
                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error rejecting holiday request {RequestId}", requestId);
                throw;
            }
        }

        public async Task<bool> CancelHolidayRequestAsync(int requestId, string cancelledBy, string? cancellationReason = null)
        {
            try
            {
                _logger.LogInformation("Cancelling holiday request {RequestId} by {CancelledBy}", requestId, cancelledBy);

                // Get holiday request (placeholder - implement with your repository)
                var holidayRequest = new HolidayRequestResponseDto
                {
                    Id = requestId,
                    EmployeeId = 1,
                    EmployeeName = "User",
                    EmployeeEmail = "user@company.com",
                    Status = "Cancelled",
                    UpdatedAt = DateTime.UtcNow
                };

                // Get user details for email notification (using EmployeeId field as legacy mapping)
                var allUsers = _userManager.Users.ToList();
                var user = allUsers.FirstOrDefault(u => u.EmployeeId == holidayRequest.EmployeeId);
                if (user != null && !string.IsNullOrWhiteSpace(user.Email))
                {
                    try
                    {
                        var managerEmail = "manager@company.com"; // This would come from your user/manager relationship
                        await _holidayEmailService.SendHolidayRequestCancelledNotificationAsync(holidayRequest, user, managerEmail);
                        _logger.LogInformation("Holiday request cancelled notification sent");
                    }
                    catch (Exception emailEx)
                    {
                        _logger.LogWarning(emailEx, "Failed to send holiday request cancelled notification");
                    }
                }

                _logger.LogInformation("Holiday request {RequestId} cancelled successfully", requestId);
                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error cancelling holiday request {RequestId}", requestId);
                throw;
            }
        }

        public async Task<HolidayRequestResponseDto> ModifyHolidayRequestAsync(int requestId, HolidayRequestSubmissionDto modifiedRequest, string modifiedBy)
        {
            try
            {
                _logger.LogInformation("Modifying holiday request {RequestId} by {ModifiedBy}", requestId, modifiedBy);

                // Validate modified request
                var validationErrors = ValidateHolidayRequest(modifiedRequest);
                if (validationErrors.Any())
                {
                    throw new ValidationException($"Modified holiday request validation failed: {string.Join(", ", validationErrors)}");
                }

                // Update holiday request (placeholder - implement with your repository)
                var holidayRequest = new HolidayRequestResponseDto
                {
                    Id = requestId,
                    EmployeeId = 1,
                    EmployeeName = "User",
                    EmployeeEmail = "user@company.com",
                    StartDate = modifiedRequest.StartDate,
                    EndDate = modifiedRequest.EndDate,
                    NumberOfDays = modifiedRequest.NumberOfDays,
                    HolidayType = modifiedRequest.HolidayType,
                    Reason = modifiedRequest.Reason,
                    Comments = modifiedRequest.Comments,
                    Status = "Pending", // Reset to pending for re-approval
                    UpdatedAt = DateTime.UtcNow,
                    IsHalfDay = modifiedRequest.IsHalfDay,
                    HalfDayType = modifiedRequest.HalfDayType
                };

                // Get user details for email notification (using EmployeeId field as legacy mapping)
                var allUsers = _userManager.Users.ToList();
                var user = allUsers.FirstOrDefault(u => u.EmployeeId == holidayRequest.EmployeeId);
                if (user != null && !string.IsNullOrWhiteSpace(user.Email))
                {
                    try
                    {
                        var managerEmail = "manager@company.com"; // This would come from your user/manager relationship
                        await _holidayEmailService.SendHolidayRequestModifiedNotificationAsync(holidayRequest, user, managerEmail);
                        _logger.LogInformation("Holiday request modified notification sent to manager");
                    }
                    catch (Exception emailEx)
                    {
                        _logger.LogWarning(emailEx, "Failed to send holiday request modified notification");
                    }
                }

                _logger.LogInformation("Holiday request {RequestId} modified successfully", requestId);
                return holidayRequest;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error modifying holiday request {RequestId}", requestId);
                throw;
            }
        }

        public Task<HolidayRequestResponseDto> GetHolidayRequestByIdAsync(int requestId)
        {
            try
            {
                _logger.LogInformation("Getting holiday request {RequestId}", requestId);

                // Get holiday request (placeholder - implement with your repository)
                var holidayRequest = new HolidayRequestResponseDto
                {
                    Id = requestId,
                    EmployeeId = 1,
                    EmployeeName = "User",
                    EmployeeEmail = "user@company.com",
                    StartDate = DateTime.Now.AddDays(7),
                    EndDate = DateTime.Now.AddDays(10),
                    NumberOfDays = 4,
                    HolidayType = "Annual Leave",
                    Reason = "Family vacation",
                    Status = "Pending",
                    CreatedAt = DateTime.UtcNow.AddDays(-1),
                    UpdatedAt = DateTime.UtcNow.AddDays(-1)
                };

                return Task.FromResult(holidayRequest);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting holiday request {RequestId}", requestId);
                throw;
            }
        }

        public Task<IEnumerable<HolidayRequestResponseDto>> GetHolidayRequestsByEmployeeAsync(int employeeId)
        {
            try
            {
                _logger.LogInformation("Getting holiday requests for employee {EmployeeId}", employeeId);

                // Get holiday requests (placeholder - implement with your repository)
                var holidayRequests = new List<HolidayRequestResponseDto>
                {
                    new HolidayRequestResponseDto
                    {
                        Id = 1,
                        EmployeeId = employeeId,
                        EmployeeName = "User",
                        EmployeeEmail = "user@company.com",
                        StartDate = DateTime.Now.AddDays(7),
                        EndDate = DateTime.Now.AddDays(10),
                        NumberOfDays = 4,
                        HolidayType = "Annual Leave",
                        Reason = "Family vacation",
                        Status = "Pending",
                        CreatedAt = DateTime.UtcNow.AddDays(-1),
                        UpdatedAt = DateTime.UtcNow.AddDays(-1)
                    }
                };

                return Task.FromResult<IEnumerable<HolidayRequestResponseDto>>(holidayRequests);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting holiday requests for employee {EmployeeId}", employeeId);
                throw;
            }
        }

        public Task<IEnumerable<HolidayRequestResponseDto>> GetPendingHolidayRequestsAsync(int managerId)
        {
            try
            {
                _logger.LogInformation("Getting pending holiday requests for manager {ManagerId}", managerId);

                // Get pending holiday requests (placeholder - implement with your repository)
                var pendingRequests = new List<HolidayRequestResponseDto>
                {
                    new HolidayRequestResponseDto
                    {
                        Id = 1,
                        EmployeeId = 1,
                        EmployeeName = "User",
                        EmployeeEmail = "user@company.com",
                        StartDate = DateTime.Now.AddDays(7),
                        EndDate = DateTime.Now.AddDays(10),
                        NumberOfDays = 4,
                        HolidayType = "Annual Leave",
                        Reason = "Family vacation",
                        Status = "Pending",
                        CreatedAt = DateTime.UtcNow.AddDays(-1),
                        UpdatedAt = DateTime.UtcNow.AddDays(-1)
                    }
                };

                return Task.FromResult<IEnumerable<HolidayRequestResponseDto>>(pendingRequests);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting pending holiday requests for manager {ManagerId}", managerId);
                throw;
            }
        }

        public Task<HolidayBalanceDto> GetHolidayBalanceAsync(int employeeId)
        {
            try
            {
                _logger.LogInformation("Getting holiday balance for employee {EmployeeId}", employeeId);

                // Get holiday balance (placeholder - implement with your repository)
                var balance = new HolidayBalanceDto
                {
                    EmployeeId = employeeId,
                    EmployeeName = "User",
                    TotalDays = 25,
                    UsedDays = 10,
                    RemainingDays = 15,
                    PendingDays = 4,
                    YearStart = new DateTime(DateTime.Now.Year, 1, 1),
                    YearEnd = new DateTime(DateTime.Now.Year, 12, 31)
                };

                return Task.FromResult(balance);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting holiday balance for employee {EmployeeId}", employeeId);
                throw;
            }
        }

        public Task<IEnumerable<string>> CheckHolidayConflictsAsync(DateTime startDate, DateTime endDate, int? employeeId = null)
        {
            try
            {
                _logger.LogInformation("Checking holiday conflicts for period {StartDate} to {EndDate}", startDate, endDate);

                // Check for conflicts (placeholder - implement with your repository)
                var conflicts = new List<string>
                {
                    "Jane Smith",
                    "Mike Johnson"
                };

                return Task.FromResult<IEnumerable<string>>(conflicts);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error checking holiday conflicts");
                throw;
            }
        }

        public async Task<int> SendPendingRequestRemindersAsync(int daysThreshold = 3)
        {
            try
            {
                _logger.LogInformation("Sending pending request reminders for requests older than {DaysThreshold} days", daysThreshold);

                var remindersSent = 0;
                var cutoffDate = DateTime.UtcNow.AddDays(-daysThreshold);

                // Get pending requests older than threshold (placeholder - implement with your repository)
                var pendingRequests = new List<HolidayRequestResponseDto>
                {
                    new HolidayRequestResponseDto
                    {
                        Id = 1,
                        EmployeeId = 1,
                        EmployeeName = "User",
                        EmployeeEmail = "user@company.com",
                        StartDate = DateTime.Now.AddDays(7),
                        EndDate = DateTime.Now.AddDays(10),
                        NumberOfDays = 4,
                        HolidayType = "Annual Leave",
                        Status = "Pending",
                        CreatedAt = cutoffDate.AddDays(-1),
                        UpdatedAt = cutoffDate.AddDays(-1)
                    }
                };

                foreach (var request in pendingRequests)
                {
                    try
                    {
                        // Get user details for email notification (using EmployeeId field as legacy mapping)
                        var allUsers = _userManager.Users.ToList();
                        var user = allUsers.FirstOrDefault(u => u.EmployeeId == request.EmployeeId);
                        if (user != null && !string.IsNullOrWhiteSpace(user.Email))
                        {
                            var managerEmail = "manager@company.com"; // This would come from your user/manager relationship
                            var daysPending = (int)(DateTime.UtcNow - request.CreatedAt).TotalDays;
                            
                            await _holidayEmailService.SendHolidayRequestPendingReminderAsync(request, user, managerEmail, daysPending);
                            remindersSent++;
                            _logger.LogInformation("Pending request reminder sent for request {RequestId}", request.Id);
                        }
                    }
                    catch (Exception emailEx)
                    {
                        _logger.LogWarning(emailEx, "Failed to send pending request reminder for request {RequestId}", request.Id);
                    }
                }

                _logger.LogInformation("Sent {RemindersSent} pending request reminders", remindersSent);
                return remindersSent;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error sending pending request reminders");
                throw;
            }
        }

        #region Private Helper Methods

        private List<string> ValidateHolidayRequest(HolidayRequestSubmissionDto request)
        {
            var errors = new List<string>();

            if (request.StartDate < DateTime.Today)
            {
                errors.Add("Start date cannot be in the past");
            }

            if (request.EndDate < request.StartDate)
            {
                errors.Add("End date cannot be before start date");
            }

            if (request.NumberOfDays <= 0)
            {
                errors.Add("Number of days must be greater than 0");
            }

            if (string.IsNullOrWhiteSpace(request.HolidayType))
            {
                errors.Add("Holiday type is required");
            }

            if (request.IsHalfDay && string.IsNullOrWhiteSpace(request.HalfDayType))
            {
                errors.Add("Half day type is required when requesting half day");
            }

            return errors;
        }

        #endregion
    }
}

